# Copyright 2025 Raza Ahmad. Licensed under Apache 2.0.

"""
Generate mock Groth16 artifacts for development.
In production, use: circom + snarkjs + ceremony for real proving/verifying keys.
"""

import json
import os
from pathlib import Path

def generate_mock_artifacts():
    """Generate mock Groth16 proving/verifying key artifacts."""
    
    build_dir = Path(__file__).parent / "build"
    build_dir.mkdir(exist_ok=True)
    
    # Mock Groth16 verifying key (VK) - JSON format used by snarkjs
    # In production, this is generated by: snarkjs groth16 export-verification-key
    vk_json = {
        "protocol": "groth16",
        "curve": "bn128",
        "nPublic": 3,  # requiredAge, insuranceProviderID, currentTimestamp
        "vk_alpha_1": [
            "20881961517175400040736011061313933718236052753712147273201869859254079368675",
            "9262547503642131121432685975572202308758993505644037141076429651485449034447",
            "1"
        ],
        "vk_beta_2": [
            [
                "6375614351688725206403015374283393846137385387536021372791840898638533154726",
                "4511626834534870392383736537800771691835404534158926993080821786766510102630"
            ],
            [
                "10307601595873709700152284273816112254676147701191060464309835616691702963480",
                "7817230099345225621852433634993555811003947744717645179637560635884330382960"
            ],
            [
                "1",
                "0"
            ]
        ],
        "vk_gamma_2": [
            [
                "10857046999023057135944570762232829481370756359578518086990519993285655852570",
                "11559732032986387107991004021392285783925812861821192530917403151452391805634"
            ],
            [
                "8495653923123431417604973247212409418986837873622013orthevideosplitting",
                "16798108137837310896154408485843033708626110116031868342845695511937071075741"
            ],
            [
                "1",
                "0"
            ]
        ],
        "vk_delta_2": [
            [
                "10857046999023057135944570762232829481370756359578518086990519993285655852570",
                "11559732032986387107991004021392285783925812861821192530917403151452391805634"
            ],
            [
                "8495653923123431417604973247212409418986837873622013878588533147770022651490",
                "16798108137837310896154408485843033708626110116031868342845695511937071075741"
            ],
            [
                "1",
                "0"
            ]
        ],
        "vk_gamma_abc": [
            [
                "11559732032986387107991004021392285783925812861821192530917403151452391805634",
                "10857046999023057135944570762232829481370756359578518086990519993285655852570"
            ],
            [
                "8495653923123431417604973247212409418986837873622013878588533147770022651490",
                "16798108137837310896154408485843033708626110116031868342845695511937071075741"
            ],
            [
                "10307601595873709700152284273816112254676147701191060464309835616691702963480",
                "7817230099345225621852433634993555811003947744717645179637560635884330382960"
            ]
        ]
    }
    
    vk_path = build_dir / "verification_key.json"
    with open(vk_path, "w") as f:
        json.dump(vk_json, f, indent=2)
    print(f"✅ Generated: {vk_path}")
    
    # Mock circuit artifacts metadata
    metadata = {
        "circuit": "eligibility",
        "version": "1.0",
        "status": "DEVELOPMENT (mock artifacts)",
        "description": "Patient eligibility verification circuit (Groth16 on BN254)",
        "inputs": {
            "private": ["patientID", "dateOfBirth", "insurancePolicyNum", "medicalHistoryHash"],
            "public": ["requiredAge", "insuranceProviderID", "currentTimestamp"]
        },
        "output": "isEligible (0 or 1)",
        "notes": [
            "For production, compile with: circom eligibility.circom --r1cs --wasm",
            "Generate VK with: snarkjs groth16 export-verification-key",
            "Run setup ceremony: snarkjs groth16 setup + snarkjs zkey contribute"
        ]
    }
    
    metadata_path = build_dir / "circuit_metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"✅ Generated: {metadata_path}")
    
    # Create README
    readme = """# Circom Circuit Artifacts

## Development Status
These are **mock artifacts** for development/testing. For production deployment:

### Build Real Artifacts
```bash
# Install dependencies
npm install -g circom snarkjs

# Compile circuit
circom eligibility.circom --r1cs --wasm --sym

# Download Powers of Tau (one-time)
wget https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_10.ptau

# Generate proving key (Phase 1)
snarkjs groth16 setup eligibility.r1cs powersOfTau28_hez_final_10.ptau eligibility_0000.zkey

# Contribute to ceremony (Phase 2)
snarkjs zkey contribute eligibility_0000.zkey eligibility_final.zkey -n="Your contribution"

# Export verification key
snarkjs groth16 export-verification-key eligibility_final.zkey verification_key.json
```

## Circuit Structure
- **Inputs (private)**: patientID, dateOfBirth, insurancePolicyNum, medicalHistoryHash
- **Inputs (public)**: requiredAge, insuranceProviderID, currentTimestamp
- **Output**: isEligible (1 if patient meets age + insurance criteria, 0 otherwise)
- **Components**: Poseidon hash (insurance validation), GreaterEqThan (age check)

## Files
- `eligibility.circom`: Circuit source code
- `build/verification_key.json`: Groth16 verification key (mock)
- `build/circuit_metadata.json`: Circuit metadata
"""
    
    readme_path = Path(__file__).parent / "README.md"
    with open(readme_path, "w") as f:
        f.write(readme)
    print(f"✅ Generated: {readme_path}")
    
    print("\n📋 Summary:")
    print(f"  Build dir: {build_dir}")
    print(f"  VK location: {vk_path}")
    print(f"  Ready for testing: ✓")

if __name__ == "__main__":
    generate_mock_artifacts()
    print("\n✨ Mock artifacts generated successfully!")
    print("   Next: Update Solana contract to load VK from build/verification_key.json")
